---

---

<!-- Program Element Historical Details -->

```{r setup3, include=FALSE}

knitr::opts_knit$set(root.dir = "~/RProjects/SturgeonPopMetrics/")

```

## Study Design & Objective

We (CDFW) use trammel nets to catch mostly adult sturgeon. Sampling occurs late summer to mid-fall (Aug-Oct) typically in Suisun and San Pablo bays. The objective is to catch and then disc tag as many sturgeon as possible. We use 100 to 200 centimeters total length (cm TL) as criteria for tagging. Fish < 100 cm TL are enumerated and measured. Fish > 200 cm TL may receive a disc tag if it is safe --- to the fish and crew --- to do so.

Sturgeon deemed "taggable" receive a single disc tag just below the dorsal fin on the right side. Disc tags are sequentially numbered with a 6-character alpha-numeric (i.e., the tag number). Along with tag number, fork length (in centimeters [cm]), trammel mesh size, and fish condition at release (good; fair; poor) are recorded. Noted too is any evidence of a captured fish having shed a disc tag and (or) if a captured fish needed to be re-tagged.

Sampling typically occurs Monday through Thursday from roughly dawn until early afternoon. The trammel net is set in locations selected by the boat operator to avoid known snags and unfavorable currents. The net is deployed cross current with the vessel downwind. On average, it takes approximately five minutes to set the net. We continuously monitor the deployed net to detect snags, tangles, marine mammal interactions, and to avoid conflicts with other vessels and hazards such as channel markers. The net is set as many times (usually 4-6) as possible each field day, with each set lasting up to 40 minutes.

We record the following information for each net set. Further, we note any unusual procedures (e.g., had to pull net early due to possible snag).

- net length
- general geographic area (e.g., Suisun Bay)
- latitude & longitude at the start of the net set
- start & end times for net set & net retrieval
- personnel (disc tagger & data recorder)
- tidal state (as ebb, floor, or slack)
- wind & wave conditions based on the Beaufort scale (0-12)
- water temperature (to nearest 0.5 degree Celsius)
- number of pinnipeds (seals or sea lions) within 50 meters of the net
- pinnipeds raiding the net (yes or no)
- other vessel interactions (yes or no)

<!-- <TODO: more narrative for study description / design here> -->
<!-- - objective with data (mark-recapture) -->

#### changes  (come up with more descriptive section name)

Up until 2002, we only disc tagged legal-sized sturgeon. Beginning in 2005, we attempted to disc tag every sturgeon but smaller fish (i.e., < 100 cm TL) proved challenging with tag placement in relation to longterm growth. 

In 2013, responding to concers from National Marine Fisheries Services (NMFS) about handling listed species we stopped disc tagging Green Sturgeon. Regulations now restrict anglers from removing Green Sturgeon out of the water, and we catch too few Green Sturgeon to make any reliable estimates using disc tag information.

In 2007 and again in 2019, we implanted passive integrated transponders (aka PIT tags) into a portion of our sturgeon catch.

## Sampling Period & Sampling Locations

This program has sampled nearly annually from 2005, prior to which sampling was irregular. It began in 1954, but sampling with some consistency did not materialize until the mid 1980s. We conduct fieldwork late summer through mid fall.

Sampling locations have favored Suisun and San Pablo bays. We do not have specific sampling stations bounded by established waypoints and thus sample whereever we think we can (1) safely fish the net and (2) maximize our catch.

<!-- <TODO: more narrative including map of sampling locations> -->

## Gear Description

<!-- drift trammel nets (construction ?) -->

Our trammel net is a passive gear type (e.g., drift net; <TODO: add citation>). It is configured as 4<-8> contiguous panels, with each panel 45.72 m (L) x m 3.66 (D) [150 ft (L) x 12 ft (D)]. 

<TODO: explain inner & outer webbing, design, etc.>

## Effort

We deploy our trammel net from the vessel's stern using a hydraulic-powered net reel. Catch and weather (e.g., currents; wind) can dictate the number of daily deployments, but typically a vessel will set the net 5&pm; times. Net set and net retrieval times are recorded to the nearest minute (as `HH:MM`).

We use set and retrieval times to calculate fishing effort (see equations below). True soak time --- or if not available estimated soak time --- is then multiplied by net length (usually fathoms).

$\text{total fishing time}=\text{nre}-\text{nss}$  

$\text{soak time}=\text{nre}-\text{nse}$  

$\text{true soak time}={(\text{nrs} - \text{nse})+0.5\times(\text{nre} - \text{nrs})+0.5\times(\text{nse} - \text{nss})}$  

$\text{estimated soak time}=0.138 + (0.687 * \text{soak time})$  

where:  
- `nss` = net set start  
- `nse` = net set end  
- `nrs` = net retrieve start  
- `nre` = net retrieve end  

<!-- *Note*: explain 0.5 in true soak time -->
*Note*: If soak time is `NA`, then estimated soak time is 1.067.

<!-- <TODO: describe soak times; number sets per location per day; Describe how gear is used per site visit (Include table summarizing number of samples per gear type and sampling period (e.g. per month) per year.)> -->

## Required Resources

At minimum, this study requires the following "big ticket" items.

- research vessel with hydraulic net reel & one tagging cradle
- at least one complete 4-panel trammel net (or raw materials to build one)
- 1-2 replacement panels (in case of in-season damage)
- serially numbered disc tags (count: ~400 to begin each season)
- PIT tags (count: ~400 to begin each season)
- 4-5 personnel
  + Vessel Mate
  + Fish & Wildlife Technician (deck hand)
  + Environmental Scientist (or similar scientific staff)
  + Scientific Aide (1 or 2 depending on needs and availability)

## Initial Sampling Purpose

??
