---

---

<!-- 21-Feb-2020 @ 1415 -->

<!-- MORE Program Element Historical Details -->

<!-- Andrew's writing below - decided for now to keep it all together for flow & readability -->

```{r setup4, include=FALSE}

knitr::opts_knit$set(root.dir = "~/RProjects/SturgeonPopMetrics/")

```

## Project History

Prior to 1954, fishing for both White Sturgeon (*Acipenser transmontanus*) and Green Sturgeon (*A. medirostris*) had been closed since 1917. On the recommendation of Fish and Game personnel, the sturgeon sport fishery reopened April 1954 with a daily bag limit of one fish &ge; 40" and no annual bag limit or seasonal closure. To further assess the future and impact of this new sport fishery, a White Sturgeon life history study began July 1954. This project’s objectives were to observe the growth of the fishery and to learn enough of the life history to evaluate and improve existing regulations [Pycha -@pycha-1956]. This work would set off a series of projects that would attempt to find out important information about the little-known data of White Sturgeon in Northern California. The studies would be labeled and funded as California project F-9-R, “A Study of Sturgeon and Striped Bass,” which was supported by Federal Aid to Fish Restoration Funds.

Sturgeon were caught using salmon trammel nets deployed in San Pablo Bay from August to November 1954. In all, 1,003 sturgeon were double tagged using variations and combinations of three different types tags and locations on the fish [Chadwick -@chadwick-1959]. Fin rays of some fish were also collected for aging. Using recapture data from previous tagging days in the season, Pycha -@pycha-1956 estimated the San Pablo Bay White Sturgeon population at just over 11,000 individuals. Although few, disc tags reported by anglers suggested a winter or spring up-stream migration and summer downstream migration of large fish. Fin ray data suggested 40" fish were roughly 8 years old. Pycha -@pycha-1956 suggested the minimum harvest limit be raised to 50" to allow for maintenance of spawning stock.

Chadwick -@chadwick-1959 analyzed disc tag returns from Pycha’s 1954 <citation> tagging study to estimate fishing mortality rate and further investigate sturgeon migration. The 1954 tagging study experienced low tag returns, in large part due to bycatch and non-reporting of tagged sturgeon in commercial salmon and shad nets. Commercial salmon and shad fishing were later outlawed in California in 1957. Understanding that most of the 1954 tag returns had probably been received by 1959, Chadwick -@chadwick-1959 decided to finalize the fishing mortality estimate for Pycha’s 1954 study. The study determined that 2-10% of the San Pablo Bay tagged sturgeon were harvested within the first year of being tagged, and that tag returns can provide useful harvest information for long-lived fish such as sturgeon. The study also found that a select few of the tagged White Sturgeon (n=1) and Green Sturgeon (n=3) had migrated along the coast and were recaptured in Oregon [Chadwick -@chadwick-1959].

From 1954 to 1963, anglers had almost no effective techniques for catching sturgeon. In 1964, anglers discovered bay shrimp (*Crago* sp.) greatly increased their efficiency catching sturgeon. Yearly party boat catches rose from three sturgeon caught in 1963 to 2,400 sturgeon caught in 1967 [Fenner and McKechnie -@fenner-1971]. A 1967-1968 study assessed how improved fishing techniques might affect harvest rate. Reward tags (\$5, ~\$30 in 2020) were used to improve reporting rates. Approximately half of the study’s sturgeon were double tagged to determine tag shedding rates between anterior and posterior below dorsal tagging locations. One thousand six hundred twelve (1,612) sturgeon were tagged in 1967 and 1,080 sturgeon were tagged in 1968. This study determined that the anterior dorsal tagging location resulted in more tag returns over time <and is where CDFW currently disc tags sturgeon to this day>. Exploitation of sturgeon was estimated at 7.3% for 1967 and 6.5% for 1968. Miller <year> estimated the population size to be approximately 115,000 sturgeon &ge; 41". Miller <year> also noted that this population size supported the stay of the 40" total length minimum for sturgeon that the regulations we currently set at [Miller -@miller-1972a]. A subsequent study on 1967-68 tag returns was also conducted by Miller. The results suggested that White Sturgeon inhabit the lower estuary during summer, fall and winter, and spawning migration upriver occurs during late winter and early spring [Miller -@miller-1972b]. 

Larval Green Sturgeon and White Sturgeon were collected in the Sacramento-San Joaquin river system by CDFW (then CDFG) in 1966, 1967, and 1968. Almost nothing was known about the time or place of spawning for sturgeon in California. The results of this important study indicated that spawning occurred upstream in the Sacramento River and that catch of sturgeon larvae in the delta was dependent on flow from the rivers above. This also supported the theory that sturgeon migrate upriver and spawn in rocky or gravel substrates [Stevens and Miller -@stevens-miller-1970]. This project’s funding would also be significant. In addition to the Federal Aid to Fish Restoration funds for the F-9-R project “A Study of Sturgeon and Striped Bass,” funding would also come from the California Department of Water Resources in cooperation with CDFG Delta Fish and Wildlife Protection Study. The Delta Fish and Wildlife Protection Study would start in 1961 to be the first time in California that entities who stood to profit from potential water exports would pay for studies to protect potentially impacted fish and wildlife [citation needed].

<!-- (cant, remember exact source, but common knowledge is true, search source!!!-IEP annual report I think). -->

Sturgeon were caught and tagged via trammel nets again in 1974. This study sought to determine the effect on survival of fin ray-clipped fish. Fish were again tagged with \$5 reward tags to increase angler response. The results yielded that pectoral ray clipped fish had substantial mortality within the first year of tagging. The study also concluded that if fin ray removal was used in conjunction with a sturgeon tagging study, the population parameter estimates derived from tag recoveries could potentially exhibit serious bias [Kohlhorst -@kohlhorst-1979]. Fin rays from fish were analyzed with other samples (mostly CPFV and trammel collected samples) to determine growth rates for 1965-1970 and 1973-1976 sturgeon samples. The study determined that growth-rate was similar for 1965-1970 and 1973-1976 fish but was lower than earlier 1954 fish. The decrease in growth-rate was not determined if it was real or due to different aging techniques [Kohlhorst et al. -@kohlhorst-et_al-1980].

Tagging for sturgeon in San Pablo Bay was again done in 1979 to report updated White Sturgeon population estimates for years 1954, 1967, 1968, 1974, and 1979. The study concluded that abundance of White Sturgeon increased from 1974 to 1979 [Kohlhorst -@kohlhorst-1980]. Abundance and mortality estimates based off CDFW tagging studies were updated in 1988 and included additional tagging years of 1984, 1985, and 1987. The results of this study estimated the exploitation rates in 1980s had increased 41% over previous years and suggested that further restrictions on the sport fishery were needed to reduce catch and support spawning stock [Kohlhorst et al. -@kohlhorst-et_al-1991]. A 72-inch maximum size limit was established in 1990, and the minimum size limit was increased 2 inches per year until a new minimum limit of 46 inches was reached by 1993 [Cech -@cech-1992; CDFW -@esr-wst].

Tagging continued intermittently in the 1990s to determine if the new 1990 fishing regulations were effective. Results from the study suggested that the new fishing regulations had reduced the exploitation rate by at least half compared to rates of the mid to late 1980s, and that fishing regulations did not need to change at the time. The study stated the that continual monitoring would need to be done to assure a sustainable population [Kohlhorst and Schaffter -@kohlhorst-shaffter-1999]. 

Disc tagging sturgeon in San Pablo and Suisun bays has continued since the early 2000s, with exceptions to a handful of years when tagging did not occur to due to personnel and equipment/vessel issues <are we sure about this?>. Historic tagging locations, gear, and methods have mostly remained the same, with few exceptions. In 2007, trammel net lengths and net soak times were reduced by half to mitigate potential pinniped interactions. From 2007 to 2019, tagging effort was mostly directed to Suisun Bay. In 2019, only the R/V *New Alosa* was used. Since 2005, mostly two vessels have been used for tagging sturgeon, but in 2018 the aging 52-year-old R/V *Striper II* was processed to be surveyed and released by the State of California (CDFW-Sportfish Date; CDFW-Andrew Danos). 

Blackburn et al. [-@blackburn-et-al-2019] developed a model using CDFW Region 3 data that aimed to evaluate the population dynamics for White Sturgeon in the Sacramento-San Joaquin Estuary and use the information to estimate the population-level response under plausible management scenarios. The idea was to develop a model that would project population growth or decline depending on exploitation rate and be able to adjust exploitation rate and “game” the system to see what that would do to the population. Blackburn et al. [-@blackburn-et-al-2019] used mark-recapture data from 2007-2016. Blackburn et al. [-@blackburn-et-al-2019] also used recent estimates of slot-limit population size of 48,000 fish age 3 and older for the model, and used 10%, 15%, and 25% spawning periodicities.
