---

---

```{r setup, include=FALSE}

knitr::opts_knit$set(root.dir = "~/RProjects/SturgeonPopMetrics")

```

```{r libraries}

# source(file = "~/RSourcedCode/methods_desc_stats.R")

library(dplyr)

```

```{r load-data}

SturgeonCpfv <- readRDS(file = "data/cpfv/SturgeonCpfv.rds")

count_all <- nrow(SturgeonCpfv)

```

```{r somevars}

# chunk creates variables needed in analytics or fig caption

years_text <- paste0(range(SturgeonCpfv[["LogYear"]]), collapse = "-")

# only blocks east of GG Bridge
blocks_sfe <- c(300:308, 488, 489)

# # for this report only White Sturgeon (assume 470 is mostly white)
# species <- c("470", "472") # all & white - for summary only
# 
# # for applying descriptive stats; fields for which stats are applied appear at
# # right commented out
# cols_desc_stats <- list(
#   c("Year", "Period", "NumMonths", "NumDays", "N"), # date
#   "NVals",                                          # vessel count
#   "ValsAsString",                                   # species code
#   "Sum",                                            # num kept
#   "Sum",                                            # num hours fished
#   "Sum",                                            # num anglers
#   "Sum"                                             # num angler hours
# )
# 
# # column names for final annual summary output (dataframe)
# new_col_names <- c(
#   "Year", "Period", "Months", "Days", "Trips", #"Vessels",
#   "SpecCode", "Catch",	"Hours",	"Anglers", "AnglerHours"
# )
# 
# # column names in dat on which we wish to perform descriptive stats per
# # `cols_desc_stats`
# mls_names <- c(
#   "LogDate", "VesselID", "SpeciesCode", "NumberKept",
#   "HoursFished", "NumberOfFishers", "AnglerHours"
# )

```


```{r subset-data}

SturgeonCpfv <- subset(SturgeonCpfv, Block %in% blocks_sfe)

count_sub <- nrow(SturgeonCpfv)

```

```{r get-summary}

cpfv <- SturgeonCpfv %>% 
  filter(Block %in% blocks_sfe & NumberKept > 0) %>% 
  group_by(LogYear) %>% 
  summarise(
    Catch = sum(NumberKept),
    # AngHours = sum(AnglerHours, na.rm = TRUE)
    NumAnglers = sum(NumberOfFishers)
  )

# adding catch per unit effort (CPUE) field (multiplying by 100 for convenience
# of working with larger numbers rather than decimals)
# summary_mls$CPUE <- (summary_mls$Catch / summary_mls$AngHours) * 100



xlsx::write.xlsx(
  cpfv,
  file = "WhiteStuESRData.xlsx",
  sheetName = "cpfv"#,
  # col.names = TRUE,
  # row.names = FALSE
)



```

```{r}

png(filename = "cpfv.png", width = 1024, height = 768, pointsize = 25)
# png(filename = "cpfv.png", width = 6, height = 4, res = 72, pointsize = 25)

# c(bottom, left, top, right)
par(mar = c(3.5, 4, 1, 4) + 0.1, bty = "u")

plot(
  x = cpfv[["LogYear"]],
  y = cpfv[["NumAnglers"]],
  type = "h",
  lwd = 10,
  lend = 2,
  col = "grey75",
  ylim = c(0, max(cpfv[["NumAnglers"]])),
  ylab = "Number of anglers (x 1000)",
  xlab = NA,
  yaxt = "n",
  xaxt = "n"
)

# range(cpfv[["NumAnglers"]])

# signif(c(seq(0, 3805, 500) / 1000), digits = 3)

axis(
  side = 2,
  at = seq(0, 3805, 500),
  labels = format(seq(0, 3805, 500) / 1000),
  las = 1
  # lwd.ticks = ,
  # hadj =
)

par(new = TRUE)

plot(
  x = cpfv[["LogYear"]],
  y = cpfv[["Catch"]],
  type = "b",
  cex = 1.1,
  col = "steelblue",
  axes = FALSE,
  ylab = NA,
  xlab = NA
)

# range(cpfv[["Catch"]])
# seq(100, 1000, 100)

axis(
  side = 4,
  at = seq(100, 1000, 100),
  labels = (seq(100, 1000, 100)) / 100,
  las = 2
  # lwd.ticks = ,
  # hadj =
)

mtext(text = "Catch (x 100)", side = 4, line = 2.5)
mtext(text = "Year", side = 1, line = 2)


axis(
  side = 1,
  at = (1980:2017)[(1980:2017) %% 5 == 0],
  labels = (1980:2017)[(1980:2017) %% 5 == 0],
  tck = -0.03,
  padj = -0.5
  # las = 2
  # lwd.ticks = 5
  # hadj =
)

axis(
  side = 1,
  at = 1980:2017,
  labels = NA,
  tck = -0.01
)

# grid()

legend(x = 2000,
       y = 975,
    # fill = c("grey75", "steelblue"),
    col = c("grey75", "steelblue"),
    pch = c(15, 1),
    legend = c("Anglers", "Catch"),
    pt.cex = 1.5, ncol = 2, box.col = "grey90", border = NA)

dev.off()

```


```{r}


plot(
  x = range(cpfv$LogYear),
  y = c(0, max(cpfv[, c("Catch", "NumAnglers")])),
  type = "n"
)

lines(
  x = cpfv[["LogYear"]],
  y = cpfv[["NumAnglers"]],
  type = "h",
  lwd = 10,
  lend = 2,
  col = "grey75"
)

par(new = T)

lines(
  x = cpfv[["LogYear"]],
  y = cpfv[["Catch"]],
  type = "b",
  # lwd = 10,
  # lend = 2,
  col = "steelblue",
  ylim = c(75, 1000),
  bty = "n"
)


# range(cpfv[["Catch"]])

```



